import type { CatalogExercise } from '../types'

/**
 * Exercise catalog: canonical names, common aliases/abbreviations, and
 * primary/secondary muscle mappings used by the heat map and insights.
 */
export const EXERCISE_CATALOG: CatalogExercise[] = [
  // ---- Chest / push ----
  {
    id: 'bench-press',
    name: 'Bench Press',
    aliases: ['bench', 'bp', 'flat bench', 'barbell bench', 'flat barbell bench', 'bench press'],
    primary: ['chest'],
    secondary: ['triceps', 'front-delts'],
  },
  {
    id: 'incline-bench-press',
    name: 'Incline Bench Press',
    aliases: ['incline bench', 'incline press', 'incline bb press', 'incline barbell'],
    primary: ['chest', 'front-delts'],
    secondary: ['triceps'],
  },
  {
    id: 'decline-bench-press',
    name: 'Decline Bench Press',
    aliases: ['decline bench', 'decline press'],
    primary: ['chest'],
    secondary: ['triceps', 'front-delts'],
  },
  {
    id: 'db-bench-press',
    name: 'Dumbbell Bench Press',
    aliases: ['db bench', 'dumbbell bench', 'db press', 'db bench press', 'dumbbell press'],
    primary: ['chest'],
    secondary: ['triceps', 'front-delts'],
  },
  {
    id: 'incline-db-press',
    name: 'Incline Dumbbell Press',
    aliases: ['incline db', 'incline db press', 'incline dumbbell', 'incline dumbbells'],
    primary: ['chest', 'front-delts'],
    secondary: ['triceps'],
  },
  {
    id: 'chest-fly',
    name: 'Chest Fly',
    aliases: ['flys', 'flyes', 'flies', 'db fly', 'dumbbell fly', 'pec fly', 'cable fly', 'cable crossover', 'pec deck', 'chest flys'],
    primary: ['chest'],
    secondary: ['front-delts'],
  },
  {
    id: 'push-up',
    name: 'Push-Up',
    aliases: ['pushups', 'push ups', 'push up', 'pushup', 'press ups', 'press up'],
    primary: ['chest'],
    secondary: ['triceps', 'front-delts', 'abs'],
    bodyweight: true,
  },
  {
    id: 'dip',
    name: 'Dips',
    aliases: ['dips', 'chest dips', 'bar dips', 'weighted dips', 'tricep dips'],
    primary: ['chest', 'triceps'],
    secondary: ['front-delts'],
    bodyweight: true,
  },
  {
    id: 'machine-chest-press',
    name: 'Machine Chest Press',
    aliases: ['chest press', 'chest press machine', 'machine press'],
    primary: ['chest'],
    secondary: ['triceps', 'front-delts'],
  },

  // ---- Shoulders ----
  {
    id: 'overhead-press',
    name: 'Overhead Press',
    aliases: ['ohp', 'military press', 'shoulder press', 'standing press', 'barbell press', 'strict press', 'overhead barbell press'],
    primary: ['front-delts', 'side-delts'],
    secondary: ['triceps', 'traps'],
  },
  {
    id: 'db-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    aliases: ['db ohp', 'db shoulder press', 'seated db press', 'dumbbell shoulder press', 'arnold press'],
    primary: ['front-delts', 'side-delts'],
    secondary: ['triceps'],
  },
  {
    id: 'lateral-raise',
    name: 'Lateral Raise',
    aliases: ['lat raise', 'lat raises', 'side raise', 'side raises', 'lateral raises', 'laterals', 'side laterals', 'db lateral raise'],
    primary: ['side-delts'],
    secondary: ['traps'],
  },
  {
    id: 'front-raise',
    name: 'Front Raise',
    aliases: ['front raises', 'db front raise', 'plate raise'],
    primary: ['front-delts'],
    secondary: [],
  },
  {
    id: 'rear-delt-fly',
    name: 'Rear Delt Fly',
    aliases: ['rear delt', 'rear delts', 'reverse fly', 'reverse flys', 'reverse flyes', 'rear delt raise', 'rear delt flys', 'reverse pec deck'],
    primary: ['rear-delts'],
    secondary: ['upper-back', 'traps'],
  },
  {
    id: 'face-pull',
    name: 'Face Pull',
    aliases: ['face pulls', 'facepulls', 'facepull', 'cable face pull'],
    primary: ['rear-delts'],
    secondary: ['traps', 'upper-back'],
  },
  {
    id: 'upright-row',
    name: 'Upright Row',
    aliases: ['upright rows'],
    primary: ['side-delts', 'traps'],
    secondary: ['biceps'],
  },
  {
    id: 'shrug',
    name: 'Shrugs',
    aliases: ['shrugs', 'db shrugs', 'barbell shrugs', 'trap shrugs'],
    primary: ['traps'],
    secondary: ['forearms'],
  },

  // ---- Back / pull ----
  {
    id: 'deadlift',
    name: 'Deadlift',
    aliases: ['deadlifts', 'dl', 'dead lift', 'conventional deadlift', 'deads'],
    primary: ['lower-back', 'glutes', 'hamstrings'],
    secondary: ['quads', 'traps', 'forearms', 'lats'],
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    aliases: ['rdl', 'rdls', 'romanian dl', 'stiff leg deadlift', 'sldl', 'stiff legged deadlift'],
    primary: ['hamstrings', 'glutes'],
    secondary: ['lower-back', 'forearms'],
  },
  {
    id: 'pull-up',
    name: 'Pull-Up',
    aliases: ['pullups', 'pull ups', 'pull up', 'pullup', 'weighted pullups', 'wide grip pullups'],
    primary: ['lats'],
    secondary: ['biceps', 'upper-back', 'forearms'],
    bodyweight: true,
  },
  {
    id: 'chin-up',
    name: 'Chin-Up',
    aliases: ['chinups', 'chin ups', 'chin up', 'chinup', 'weighted chins', 'chins'],
    primary: ['lats', 'biceps'],
    secondary: ['upper-back', 'forearms'],
    bodyweight: true,
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    aliases: ['pulldown', 'pulldowns', 'lat pulldowns', 'lat pull down', 'pull down', 'cable pulldown'],
    primary: ['lats'],
    secondary: ['biceps', 'upper-back'],
  },
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    aliases: ['rows', 'row', 'bb row', 'bent over row', 'bent-over row', 'barbell rows', 'pendlay row', 'bent rows'],
    primary: ['lats', 'upper-back'],
    secondary: ['biceps', 'rear-delts', 'lower-back', 'forearms'],
  },
  {
    id: 'db-row',
    name: 'Dumbbell Row',
    aliases: ['db row', 'db rows', 'dumbbell rows', 'one arm row', 'single arm row', 'one arm db row'],
    primary: ['lats', 'upper-back'],
    secondary: ['biceps', 'rear-delts', 'forearms'],
  },
  {
    id: 'cable-row',
    name: 'Cable Row',
    aliases: [
      'seated row', 'seated rows', 'cable rows', 'seated cable row', 'low row', 'machine row',
      'chest supported row', 'supported row', 'chest row',
    ],
    primary: ['lats', 'upper-back'],
    secondary: ['biceps', 'rear-delts'],
  },
  {
    id: 't-bar-row',
    name: 'T-Bar Row',
    aliases: ['t bar row', 'tbar row', 't-bar rows'],
    primary: ['lats', 'upper-back'],
    secondary: ['biceps', 'rear-delts', 'lower-back'],
  },
  {
    id: 'back-extension',
    name: 'Back Extension',
    aliases: ['back extensions', 'hyperextension', 'hyperextensions', 'hypers', '45 degree back extension'],
    primary: ['lower-back'],
    secondary: ['glutes', 'hamstrings'],
    bodyweight: true,
  },
  {
    id: 'good-morning',
    name: 'Good Morning',
    aliases: ['good mornings', 'goodmornings'],
    primary: ['hamstrings', 'lower-back'],
    secondary: ['glutes'],
  },
  {
    id: 'rack-pull',
    name: 'Rack Pull',
    aliases: ['rack pulls'],
    primary: ['lower-back', 'traps'],
    secondary: ['glutes', 'hamstrings', 'forearms', 'lats'],
  },

  // ---- Arms ----
  {
    id: 'bicep-curl',
    name: 'Bicep Curl',
    aliases: ['curls', 'curl', 'bicep curls', 'biceps curl', 'db curl', 'db curls', 'dumbbell curl', 'dumbbell curls', 'barbell curl', 'bb curl', 'ez bar curl', 'ez curl', 'some curls'],
    primary: ['biceps'],
    secondary: ['forearms'],
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    aliases: ['hammer curls', 'hammers', 'hammercurls'],
    primary: ['biceps', 'forearms'],
    secondary: [],
  },
  {
    id: 'preacher-curl',
    name: 'Preacher Curl',
    aliases: ['preacher curls', 'preacher', 'scott curl'],
    primary: ['biceps'],
    secondary: ['forearms'],
  },
  {
    id: 'incline-curl',
    name: 'Incline Curl',
    aliases: ['incline curls', 'incline db curl', 'incline dumbbell curl'],
    primary: ['biceps'],
    secondary: ['forearms'],
  },
  {
    id: 'cable-curl',
    name: 'Cable Curl',
    aliases: ['cable curls', 'bayesian curl'],
    primary: ['biceps'],
    secondary: ['forearms'],
  },
  {
    id: 'tricep-pushdown',
    name: 'Tricep Pushdown',
    aliases: ['pushdown', 'pushdowns', 'tricep pushdowns', 'rope pushdown', 'cable pushdown', 'tricep extension cable', 'triceps pushdown', 'rope extensions', 'tricep pulldown', 'tricep pull down', 'triceps pulldown'],
    primary: ['triceps'],
    secondary: [],
  },
  {
    id: 'skull-crusher',
    name: 'Skull Crusher',
    aliases: ['skull crushers', 'skullcrushers', 'lying tricep extension', 'french press', 'ez bar skull crusher'],
    primary: ['triceps'],
    secondary: [],
  },
  {
    id: 'overhead-tricep-extension',
    name: 'Overhead Tricep Extension',
    aliases: ['overhead extension', 'overhead extensions', 'tricep extension', 'tricep extensions', 'overhead tricep', 'french curl'],
    primary: ['triceps'],
    secondary: [],
  },
  {
    id: 'close-grip-bench',
    name: 'Close-Grip Bench Press',
    aliases: ['close grip bench', 'cgbp', 'close grip', 'close-grip bench'],
    primary: ['triceps', 'chest'],
    secondary: ['front-delts'],
  },
  {
    id: 'wrist-curl',
    name: 'Wrist Curl',
    aliases: ['wrist curls', 'forearm curls', 'reverse wrist curl'],
    primary: ['forearms'],
    secondary: [],
  },

  // ---- Legs ----
  {
    id: 'squat',
    name: 'Squat',
    aliases: ['squats', 'back squat', 'back squats', 'barbell squat', 'bb squat', 'high bar squat', 'low bar squat'],
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings', 'adductors', 'lower-back', 'abs'],
  },
  {
    id: 'front-squat',
    name: 'Front Squat',
    aliases: ['front squats', 'fs'],
    primary: ['quads'],
    secondary: ['glutes', 'abs', 'upper-back'],
  },
  {
    id: 'goblet-squat',
    name: 'Goblet Squat',
    aliases: ['goblet squats', 'goblet'],
    primary: ['quads', 'glutes'],
    secondary: ['abs'],
  },
  {
    id: 'hack-squat',
    name: 'Hack Squat',
    aliases: ['hack squats', 'hack'],
    primary: ['quads'],
    secondary: ['glutes', 'adductors'],
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    aliases: ['leg press machine', 'legpress', 'leg presses'],
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings', 'adductors'],
  },
  {
    id: 'lunge',
    name: 'Lunges',
    aliases: ['lunges', 'walking lunges', 'walking lunge', 'db lunges', 'reverse lunges', 'reverse lunge'],
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings', 'adductors'],
    bodyweight: true,
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    aliases: ['bulgarian split squats', 'bulgarians', 'bss', 'split squat', 'split squats', 'rear foot elevated split squat'],
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings', 'adductors'],
    bodyweight: true,
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    aliases: ['leg extensions', 'leg ext', 'quad extension', 'quad extensions'],
    primary: ['quads'],
    secondary: [],
  },
  {
    id: 'leg-curl',
    name: 'Leg Curl',
    aliases: ['leg curls', 'hamstring curl', 'hamstring curls', 'lying leg curl', 'seated leg curl', 'ham curls', 'ham curl'],
    primary: ['hamstrings'],
    secondary: [],
  },
  {
    id: 'hip-thrust',
    name: 'Hip Thrust',
    aliases: ['hip thrusts', 'hip thrust machine', 'barbell hip thrust', 'glute bridge', 'glute bridges'],
    primary: ['glutes'],
    secondary: ['hamstrings', 'quads'],
  },
  {
    id: 'calf-raise',
    name: 'Calf Raise',
    aliases: ['calf raises', 'calves', 'calfs', 'standing calf raise', 'seated calf raise', 'calf press', 'standing calves', 'seated calves'],
    primary: ['calves'],
    secondary: [],
  },
  {
    id: 'hip-adduction',
    name: 'Hip Adduction',
    aliases: ['adduction', 'adductor machine', 'adductors machine', 'inner thigh machine'],
    primary: ['adductors'],
    secondary: [],
  },
  {
    id: 'hip-abduction',
    name: 'Hip Abduction',
    aliases: ['abduction', 'abductor machine', 'abductors machine', 'outer thigh machine'],
    primary: ['glutes'],
    secondary: [],
  },
  {
    id: 'step-up',
    name: 'Step-Up',
    aliases: ['step ups', 'stepups', 'step up', 'db step ups'],
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings'],
    bodyweight: true,
  },

  // ---- Core ----
  {
    id: 'plank',
    name: 'Plank',
    aliases: ['planks', 'front plank'],
    primary: ['abs'],
    secondary: ['obliques', 'lower-back'],
    bodyweight: true,
  },
  {
    id: 'side-plank',
    name: 'Side Plank',
    aliases: ['side planks'],
    primary: ['obliques'],
    secondary: ['abs'],
    bodyweight: true,
  },
  {
    id: 'crunch',
    name: 'Crunches',
    aliases: ['crunches', 'ab crunches', 'cable crunch', 'cable crunches', 'machine crunch'],
    primary: ['abs'],
    secondary: [],
    bodyweight: true,
  },
  {
    id: 'sit-up',
    name: 'Sit-Up',
    aliases: ['situps', 'sit ups', 'sit up', 'situp', 'decline situps'],
    primary: ['abs'],
    secondary: ['obliques'],
    bodyweight: true,
  },
  {
    id: 'leg-raise',
    name: 'Leg Raise',
    aliases: ['leg raises', 'hanging leg raise', 'hanging leg raises', 'lying leg raise', 'knee raises', 'hanging knee raises'],
    primary: ['abs'],
    secondary: ['obliques'],
    bodyweight: true,
  },
  {
    id: 'russian-twist',
    name: 'Russian Twist',
    aliases: ['russian twists', 'twists'],
    primary: ['obliques'],
    secondary: ['abs'],
    bodyweight: true,
  },
  {
    id: 'ab-wheel',
    name: 'Ab Wheel Rollout',
    aliases: ['ab wheel', 'ab rollout', 'rollouts', 'ab roller'],
    primary: ['abs'],
    secondary: ['obliques', 'lats'],
    bodyweight: true,
  },
  {
    id: 'dead-bug',
    name: 'Dead Bug',
    aliases: ['dead bugs', 'deadbugs'],
    primary: ['abs'],
    secondary: [],
    bodyweight: true,
  },

  // ---- Olympic / full body ----
  {
    id: 'clean',
    name: 'Power Clean',
    aliases: ['cleans', 'power clean', 'power cleans', 'hang clean', 'hang cleans'],
    primary: ['glutes', 'hamstrings', 'traps'],
    secondary: ['quads', 'lower-back', 'forearms', 'side-delts'],
  },
  {
    id: 'snatch',
    name: 'Snatch',
    aliases: ['snatches', 'power snatch', 'hang snatch'],
    primary: ['glutes', 'hamstrings', 'traps'],
    secondary: ['quads', 'lower-back', 'side-delts'],
  },
  {
    id: 'push-press',
    name: 'Push Press',
    aliases: ['push presses'],
    primary: ['front-delts', 'side-delts'],
    secondary: ['triceps', 'quads', 'glutes'],
  },
  {
    id: 'thruster',
    name: 'Thruster',
    aliases: ['thrusters'],
    primary: ['quads', 'front-delts'],
    secondary: ['glutes', 'triceps'],
  },
  {
    id: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    aliases: ['kb swing', 'kb swings', 'kettlebell swings', 'swings'],
    primary: ['glutes', 'hamstrings'],
    secondary: ['lower-back', 'front-delts', 'forearms'],
  },
  {
    id: 'farmers-carry',
    name: "Farmer's Carry",
    aliases: ['farmers walk', 'farmers carry', 'farmer walk', 'farmers walks', 'carries'],
    primary: ['forearms', 'traps'],
    secondary: ['abs', 'obliques'],
  },
  {
    id: 'burpee',
    name: 'Burpees',
    aliases: ['burpees'],
    primary: ['chest', 'quads'],
    secondary: ['abs', 'front-delts', 'triceps'],
    bodyweight: true,
  },
]

const byId = new Map(EXERCISE_CATALOG.map((e) => [e.id, e]))

export function getExercise(id: string): CatalogExercise | undefined {
  return byId.get(id)
}
